### ISSUE TITLE
Implement Fizzbuzz logic and Create Test Function

### ISSUE THREAD

**Issue by PavithraUmakanthan** [PavithraUmakanthan/ES6_fizzbuzz#4]

**Comment by PavithraUmakanthan** [comment]
Updated the code as per Stephanie's feedback and pushed to the Github.

**Comment by dougireton** [comment]
I assume this issue should be closed @PavithraUmakanthan?

**Comment by PavithraUmakanthan** [comment]
Yes @dougireton. I will close it.
