### ISSUE TITLE
Create a Test file

### ISSUE THREAD

**Issue by PavithraUmakanthan** [PavithraUmakanthan/ES6_fizzbuzz#5]

**Comment by stephanielingwood** [comment]
Until now, you've been testing your Fizzbuzz function via a function in the same file. 

Now, we're going to make it more official: you'll move the function out into its own file, and set up specific functions as unit tests. 

## Step 1: Move the existing test function to a `test.js` file
- Remove the test function from the `fizzbuzz` file, and add it to the `test.js` file
- Now, the challenge is figuring out how to call the fizzbuzz function from a different file. Check out `require` and `exports` in Node.js. (Good resource: https://adrianmejia.com/blog/2016/08/12/getting-started-with-node-js-modules-require-exports-imports-npm-and-beyond/) . Note that you can't use the ES6 `import` in Node...yet.
- At this point, you should be able to run `test.js` and have the `test` function work the same way it did before.

## Step 2: Create unit tests
- Create an "assertEqual" function. It should take in two values, and return `true` if they're the same, and `false` if they're not
- Create a function for each of your four test cases (fizz, buzz, fizzbuzz, and a number). These functions are your "unit tests". Each function should call the `fizzbuzz` function, and then use the `assertEqual` function to test whether the returned value is correct.
- Each unit test should have a name and a description. Those should be used to print to the console. If your test called, say, "Print fizz for numbers divisible by 3"  passes (e.g. the value is what you expect), you should see:
```
Print fizz for numbers divisible by 3
- passing: returned 'fizz' when called with the number 3 // fizz is the value returned by the fizzbuzz function
```
- If the test fails, you should see: 
```
Print fizz for numbers divisible by 3
- failed: returned 'foo' when called with the number 3 // foo is the value returned by the fizzbuzz function
```
- When you're done with this step, you should be able to run `test.js`, and see the results of your four unit tests printed to the console.

**Comment by PavithraUmakanthan** [comment]
Created test file and unit tests. Created a branch - test_fizzbuzz & Pushed my code to the Github.
